server:
  port: 9898

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    diver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: wjs123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*